name: Create VPC with EC2 Instances

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Check AWS Authentication
        run: |
          aws sts get-caller-identity
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
            region: us-east-1

      - name: Debug AWS Environment Variables
        run: |
              echo "AWS Access Key: $AWS_ACCESS_KEY_ID"
              echo "AWS Secret Key: $AWS_SECRET_ACCESS_KEY"
              echo "AWS Region: $region"
        env:
              AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
              region: us-east-1


      - name: Terraform Init
        run: 
            terraform init
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
            region: us-east-1

      - name: Terraform Plan
        run: |
              terraform plan \
                -var="access_key=${{ secrets.ACCESS_KEY }}" \
                -var="secret_key=${{ secrets.SECRET_KEY }}" \
                -var="region=us-east-1"
        env:
              AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
              region: us-east-1
    
      - name: Terraform Apply
        run: |
              terraform apply -auto-approve \
                -var="access_key=${{ secrets.ACCESS_KEY }}" \
                -var="secret_key=${{ secrets.SECRET_KEY }}" \
                -var="region=us-east-1"
        env:
              AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
              region: us-east-1
              
            
        